# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_feed.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta_feed.proto\"$\n\x12RegisterJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\"#\n\x11GetBatchesRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"6\n\x06Sample\x12\x0f\n\x07\x62\x61tchid\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\t\"z\n\x13RegisterJobResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1f\n\x17successfully_registered\x18\x02 \x01(\x08\x12\x19\n\x11\x62\x61tches_per_epoch\x18\x03 \x01(\x05\x12\x16\n\x0e\x64\x61taset_length\x18\x04 \x01(\x05\x32\x94\x01\n\x0b\x44\x61tasetFeed\x12\x1c\n\x08shutdown\x12\x06.Empty\x1a\x06.Empty\"\x00\x12:\n\x0bregisterjob\x12\x13.RegisterJobRequest\x1a\x14.RegisterJobResponse\"\x00\x12+\n\ngetBatches\x12\x12.GetBatchesRequest\x1a\x07.Sample\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_feed_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERJOBREQUEST._serialized_start=19
  _REGISTERJOBREQUEST._serialized_end=55
  _GETBATCHESREQUEST._serialized_start=57
  _GETBATCHESREQUEST._serialized_end=92
  _MESSAGERESPONSE._serialized_start=94
  _MESSAGERESPONSE._serialized_end=128
  _EMPTY._serialized_start=130
  _EMPTY._serialized_end=137
  _SAMPLE._serialized_start=139
  _SAMPLE._serialized_end=193
  _REGISTERJOBRESPONSE._serialized_start=195
  _REGISTERJOBRESPONSE._serialized_end=317
  _DATASETFEED._serialized_start=320
  _DATASETFEED._serialized_end=468
# @@protoc_insertion_point(module_scope)
