# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_feed_pb2 as data__feed__pb2


class DatasetFeedStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.shutdown = channel.unary_unary(
                '/DatasetFeed/shutdown',
                request_serializer=data__feed__pb2.Empty.SerializeToString,
                response_deserializer=data__feed__pb2.Empty.FromString,
                )
        self.registerjob = channel.unary_unary(
                '/DatasetFeed/registerjob',
                request_serializer=data__feed__pb2.RegisterJobRequest.SerializeToString,
                response_deserializer=data__feed__pb2.RegisterJobResponse.FromString,
                )
        self.getBatches = channel.unary_unary(
                '/DatasetFeed/getBatches',
                request_serializer=data__feed__pb2.GetBatchesRequest.SerializeToString,
                response_deserializer=data__feed__pb2.Sample.FromString,
                )


class DatasetFeedServicer(object):
    """Missing associated documentation comment in .proto file."""

    def shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def registerjob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatasetFeedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.shutdown,
                    request_deserializer=data__feed__pb2.Empty.FromString,
                    response_serializer=data__feed__pb2.Empty.SerializeToString,
            ),
            'registerjob': grpc.unary_unary_rpc_method_handler(
                    servicer.registerjob,
                    request_deserializer=data__feed__pb2.RegisterJobRequest.FromString,
                    response_serializer=data__feed__pb2.RegisterJobResponse.SerializeToString,
            ),
            'getBatches': grpc.unary_unary_rpc_method_handler(
                    servicer.getBatches,
                    request_deserializer=data__feed__pb2.GetBatchesRequest.FromString,
                    response_serializer=data__feed__pb2.Sample.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DatasetFeed', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DatasetFeed(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatasetFeed/shutdown',
            data__feed__pb2.Empty.SerializeToString,
            data__feed__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def registerjob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatasetFeed/registerjob',
            data__feed__pb2.RegisterJobRequest.SerializeToString,
            data__feed__pb2.RegisterJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getBatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DatasetFeed/getBatches',
            data__feed__pb2.GetBatchesRequest.SerializeToString,
            data__feed__pb2.Sample.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
