task: train
batch_size: 128
source_system: s3
data_dir: /Users/patrickwatters/Projects/datasets/sdl-cifar10
s3_bucket: sdl-cifar10
redis_host: test-001.rdior4.0001.usw2.cache.amazonaws.com
#redis_host: 10.0.1.197 #private ip
redis_port: 6379
dataload_lambda: lambda_dataloader
gprc_port: 50052