# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cms.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cms.proto',
  package='cms',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tcms.proto\x12\x03\x63ms\"@\n\x1aRegisterTrainingJobMessage\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"n\n\x1bRegisterTrainingJobResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x02 \x01(\t\x12\x12\n\nregistered\x18\x03 \x01(\x08\x12\x19\n\x11\x62\x61tches_per_epoch\x18\x04 \x01(\x05\"4\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08received\x18\x02 \x01(\x08\x32\xb2\x01\n\x16\x43\x61\x63heManagementService\x12]\n\x16RegisterNewTrainingJob\x12\x1f.cms.RegisterTrainingJobMessage\x1a .cms.RegisterTrainingJobResponse\"\x00\x12\x39\n\x11GetServerResponse\x12\x0c.cms.Message\x1a\x14.cms.MessageResponse\"\x00\x62\x06proto3'
)




_REGISTERTRAININGJOBMESSAGE = _descriptor.Descriptor(
  name='RegisterTrainingJobMessage',
  full_name='cms.RegisterTrainingJobMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='cms.RegisterTrainingJobMessage.job_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='cms.RegisterTrainingJobMessage.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=82,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='cms.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='cms.Message.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=110,
)


_REGISTERTRAININGJOBRESPONSE = _descriptor.Descriptor(
  name='RegisterTrainingJobResponse',
  full_name='cms.RegisterTrainingJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='cms.RegisterTrainingJobResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='cms.RegisterTrainingJobResponse.dataset', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='registered', full_name='cms.RegisterTrainingJobResponse.registered', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batches_per_epoch', full_name='cms.RegisterTrainingJobResponse.batches_per_epoch', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=222,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='cms.MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='cms.MessageResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='received', full_name='cms.MessageResponse.received', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=276,
)

DESCRIPTOR.message_types_by_name['RegisterTrainingJobMessage'] = _REGISTERTRAININGJOBMESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['RegisterTrainingJobResponse'] = _REGISTERTRAININGJOBRESPONSE
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterTrainingJobMessage = _reflection.GeneratedProtocolMessageType('RegisterTrainingJobMessage', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERTRAININGJOBMESSAGE,
  '__module__' : 'cms_pb2'
  # @@protoc_insertion_point(class_scope:cms.RegisterTrainingJobMessage)
  })
_sym_db.RegisterMessage(RegisterTrainingJobMessage)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'cms_pb2'
  # @@protoc_insertion_point(class_scope:cms.Message)
  })
_sym_db.RegisterMessage(Message)

RegisterTrainingJobResponse = _reflection.GeneratedProtocolMessageType('RegisterTrainingJobResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERTRAININGJOBRESPONSE,
  '__module__' : 'cms_pb2'
  # @@protoc_insertion_point(class_scope:cms.RegisterTrainingJobResponse)
  })
_sym_db.RegisterMessage(RegisterTrainingJobResponse)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'cms_pb2'
  # @@protoc_insertion_point(class_scope:cms.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)



_CACHEMANAGEMENTSERVICE = _descriptor.ServiceDescriptor(
  name='CacheManagementService',
  full_name='cms.CacheManagementService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=279,
  serialized_end=457,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterNewTrainingJob',
    full_name='cms.CacheManagementService.RegisterNewTrainingJob',
    index=0,
    containing_service=None,
    input_type=_REGISTERTRAININGJOBMESSAGE,
    output_type=_REGISTERTRAININGJOBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetServerResponse',
    full_name='cms.CacheManagementService.GetServerResponse',
    index=1,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CACHEMANAGEMENTSERVICE)

DESCRIPTOR.services_by_name['CacheManagementService'] = _CACHEMANAGEMENTSERVICE

# @@protoc_insertion_point(module_scope)
