# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_feed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_feed.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x64\x61ta_feed.proto\"$\n\x12RegisterJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\"#\n\x11GetBatchesRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x05\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"6\n\x06Sample\x12\x0f\n\x07\x62\x61tchid\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\t2\x90\x01\n\x0b\x44\x61tasetFeed\x12\x1c\n\x08shutdown\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x36\n\x0bregisterjob\x12\x13.RegisterJobRequest\x1a\x10.MessageResponse\"\x00\x12+\n\ngetBatches\x12\x12.GetBatchesRequest\x1a\x07.Sample\"\x00\x62\x06proto3')
)




_REGISTERJOBREQUEST = _descriptor.Descriptor(
  name='RegisterJobRequest',
  full_name='RegisterJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='RegisterJobRequest.job_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=55,
)


_GETBATCHESREQUEST = _descriptor.Descriptor(
  name='GetBatchesRequest',
  full_name='GetBatchesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='GetBatchesRequest.job_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=92,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='MessageResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=128,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=137,
)


_SAMPLE = _descriptor.Descriptor(
  name='Sample',
  full_name='Sample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batchid', full_name='Sample.batchid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='Sample.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='Sample.label', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=193,
)

DESCRIPTOR.message_types_by_name['RegisterJobRequest'] = _REGISTERJOBREQUEST
DESCRIPTOR.message_types_by_name['GetBatchesRequest'] = _GETBATCHESREQUEST
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Sample'] = _SAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterJobRequest = _reflection.GeneratedProtocolMessageType('RegisterJobRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERJOBREQUEST,
  __module__ = 'data_feed_pb2'
  # @@protoc_insertion_point(class_scope:RegisterJobRequest)
  ))
_sym_db.RegisterMessage(RegisterJobRequest)

GetBatchesRequest = _reflection.GeneratedProtocolMessageType('GetBatchesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETBATCHESREQUEST,
  __module__ = 'data_feed_pb2'
  # @@protoc_insertion_point(class_scope:GetBatchesRequest)
  ))
_sym_db.RegisterMessage(GetBatchesRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGERESPONSE,
  __module__ = 'data_feed_pb2'
  # @@protoc_insertion_point(class_scope:MessageResponse)
  ))
_sym_db.RegisterMessage(MessageResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'data_feed_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

Sample = _reflection.GeneratedProtocolMessageType('Sample', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLE,
  __module__ = 'data_feed_pb2'
  # @@protoc_insertion_point(class_scope:Sample)
  ))
_sym_db.RegisterMessage(Sample)



_DATASETFEED = _descriptor.ServiceDescriptor(
  name='DatasetFeed',
  full_name='DatasetFeed',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=196,
  serialized_end=340,
  methods=[
  _descriptor.MethodDescriptor(
    name='shutdown',
    full_name='DatasetFeed.shutdown',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='registerjob',
    full_name='DatasetFeed.registerjob',
    index=1,
    containing_service=None,
    input_type=_REGISTERJOBREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getBatches',
    full_name='DatasetFeed.getBatches',
    index=2,
    containing_service=None,
    input_type=_GETBATCHESREQUEST,
    output_type=_SAMPLE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATASETFEED)

DESCRIPTOR.services_by_name['DatasetFeed'] = _DATASETFEED

# @@protoc_insertion_point(module_scope)
